productpage:
  namespace: student28-bookinfo-prd
  image: ghcr.io/piyanatnine/bookinfo-productpage
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.opsta.net
  path: "/student28/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-productpage-mongodb:27017/productpage
  MONGO_DB_USERNAME: productpage
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-prd-productpage-mongodb-secret: mongodb-password